// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxU-a4TS9locs--nIflbxegQB1R3QrGU',
    appId: '1:90427237689:web:d061d5d5a156ea9fc174e8',
    messagingSenderId: '90427237689',
    projectId: 'donora-f67f2',
    authDomain: 'donora-f67f2.firebaseapp.com',
    storageBucket: 'donora-f67f2.firebasestorage.app',
    measurementId: 'G-40RWEJSXYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLAm5xD9vRRyCUggCgBx9_df6rq6MwvI',
    appId: '1:90427237689:android:71bcfebf623fd592c174e8',
    messagingSenderId: '90427237689',
    projectId: 'donora-f67f2',
    storageBucket: 'donora-f67f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCop_Q-ViuLgeguDATFR1f1awo02iaukm4',
    appId: '1:90427237689:ios:974448b2a4f9fa67c174e8',
    messagingSenderId: '90427237689',
    projectId: 'donora-f67f2',
    storageBucket: 'donora-f67f2.firebasestorage.app',
    iosBundleId: 'com.example.donoraDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCop_Q-ViuLgeguDATFR1f1awo02iaukm4',
    appId: '1:90427237689:ios:974448b2a4f9fa67c174e8',
    messagingSenderId: '90427237689',
    projectId: 'donora-f67f2',
    storageBucket: 'donora-f67f2.firebasestorage.app',
    iosBundleId: 'com.example.donoraDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKxU-a4TS9locs--nIflbxegQB1R3QrGU',
    appId: '1:90427237689:web:cad720f37094a038c174e8',
    messagingSenderId: '90427237689',
    projectId: 'donora-f67f2',
    authDomain: 'donora-f67f2.firebaseapp.com',
    storageBucket: 'donora-f67f2.firebasestorage.app',
    measurementId: 'G-91PVMH1RB2',
  );
}
